// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// ServerError defines model for ServerError.
type ServerError struct {
	Error string `json:"error"`
}

// VersionCheck defines model for VersionCheck.
type VersionCheck struct {
	Version string `json:"version"`
}
