repositories:
  - name: mongodb
    url: https://mongodb.github.io/helm-charts 

releases:

  - name: db
    namespace: apps
    createNamespace: true
    chart: ./db/mongo-community-helm/mongo-community
    version: 1.3.10
    wait: true
    waitForJobs: true
    set:
      - name: username
        value: {{ requiredEnv "DB_ROOT_USERNAME" }}
      - name: password
        value: {{ requiredEnv "DB_ROOT_PASSWORD" }}
      - name: database
        value: admin
      - name: replicas
        value: 1
      - name: persistenceType
        value: local
      - name: compressionType
        value: zstd
    installed: true

  - name: api
    namespace: apps
    createNamespace: true
    chart: ./api
    # wait: true
    # waitForJobs: true
    needs:
      - db
    set:
      - name: image.name
        value: {{ requiredEnv "IMAGE_REGISTRY_URL" }}/{{ requiredEnv "COMPOSE_PROJECT_NAME" }}
      - name: api.devMode
        value: {{ requiredEnv "API_DEV_MODE" }}
      - name: api.port
        value: {{ requiredEnv "API_PORT" }}
      - name: db.name
        value: {{ requiredEnv "DB_NAME" }}
      - name: db.auth.rootUser
        value: {{ requiredEnv "DB_ROOT_USERNAME" }}
      - name: db.auth.rootPassword
        value: {{ requiredEnv "DB_ROOT_PASSWORD" }}
  