repositories:
  - name: mongodb
    url: https://mongodb.github.io/helm-charts 

releases:

  - name: db
    namespace: apps
    createNamespace: true
    chart: ./db/mongo
    version: 1.3.10
    wait: true
    waitForJobs: true
    set:
      - name: version
        value: "4.2.6"
      - name: replicas
        value: 1
      - name: username
        value: {{ requiredEnv "DB_ROOT_USERNAME" }}
      - name: password
        value: {{ requiredEnv "DB_ROOT_PASSWORD" }}
      - name: database
        value: admin
      - name: persistenceType
        value: local
      - name: compressionType
        value: zstd
      - name: memoryMin
        value: 2000M
      - name: memoryMax
        value: 2000M
      - name: cpuMin
        value: 2000m
      - name: cpuMax
        value: 2000m
    installed: true

  - name: api
    namespace: apps
    createNamespace: true
    chart: ./api
    needs:
      - db
    set:
      - name: api.replicas
        value: 1
      - name: image.name
        value: {{ requiredEnv "IMAGE_REGISTRY_URL" }}/{{ requiredEnv "COMPOSE_PROJECT_NAME" }}
      - name: api.devMode
        value: {{ requiredEnv "API_DEV_MODE" }}
      - name: api.ginMode
        value: {{ requiredEnv "GIN_MODE" }}
      - name: api.internalPort
        value: {{ requiredEnv "API_PORT" }}
      - name: db.name
        value: {{ requiredEnv "DB_NAME" }}
      - name: db.auth.rootUser
        value: {{ requiredEnv "DB_ROOT_USERNAME" }}
      - name: db.auth.rootPassword
        value: {{ requiredEnv "DB_ROOT_PASSWORD" }}
  