apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api.fullname" . }}-db-credentials
type: Opaque
stringData:
  root_username: {{ .Values.db.auth.rootUser }}
  root_password: {{ .Values.db.auth.rootPassword }}