apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}
spec:
  selector:
    app: {{ template "api.fullname" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.api.externalPort }}
      targetPort: {{ .Values.api.internalPort }}