// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// User defines model for User.
type User struct {
	Email     string `json:"email" validate:"required,email"`
	FirstName string `json:"firstName" validate:"required,alpha"`
	LastName  string `json:"lastName" validate:"required,alpha"`
}

// Users defines model for Users.
type Users = []User

// UsersAdded defines model for UsersAdded.
type UsersAdded struct {
	NumAdded     int    `json:"numAdded"`
	NumExisted   int    `json:"numExisted"`
	NumRequested int    `json:"numRequested"`
	Status       string `json:"status"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Offset The number of items to skip before starting to collect the result set
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Sort Sort by this field
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// AddUsersJSONRequestBody defines body for AddUsers for application/json ContentType.
type AddUsersJSONRequestBody = Users
