openapi: 3.0.0
info:
  # title: Openapi-codegen
  title: {{ cookiecutter.project_name }}
  version: 1.0.0
servers:
  - url: "http://localhost:8888/api/v1"
    description: Running locally for development
  - url: "http://localhost:8887/api/v1"
    description: Mockserver for quick development
  - url: "http://kubernetes.docker.internal/api/v1"
    description: Local Minikube (Mac)
paths:
  /version:
    get:
      tags:
        - version
      summary: Get API Version
      operationId: getVersion
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionCheck'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /health:
    get:
      tags:
        - health
      summary: Server Health Check
      operationId: getHealth
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '503':
          description: Server Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    GoogleOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            read: Grants read access
            write: Grants write access
  schemas:
    VersionCheck:
      type: object
      required:
        - version
      properties:
        version:
          type: string
          example: 1.0.0
    HealthCheck:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: OK
    ServerError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: Internal Server Error
    RequestStats:
      type: object
      required:
        - requestRecieved
        - requestReturned
        - DBQueryTime
      properties:
        requestRecieved:
          type: string
          format: date-time
          example: "2023-02-15T22:27:51.254590+00:00"
        requestReturned:
          type: string
          format: date-time
          example: "2023-02-15T22:27:51.254590+00:00"
        DBQueryTime:
          type: number
          format: float
          example: 0.0001
    PaginationStats:
      type: object
      required:
        - total
        - limit
        - offset
        - returned
      properties:
        total:
          type: integer
          example: 100
        limit:
          type: integer
          example: 10
        offset:
          type: integer
          example: 0
        returned:
          type: integer
          example: 10
    GooglePubSubPushMessage:
      type: object
      properties:
        attributes:
          type: object
          example:
            googclient_schemaencoding: "JSON"
            googclient_schemarevisionid: "7ae21c7e"
            id: "e6c876cf-f522-48ff-831d-6a414464c00f"
            source: "canwsl-15"
            specversion: "1.0"
            time: "2023-02-15T22:27:51.254590+00:00"
            type: "Element"
        data: 
          type: string
          example: "eyJmaXJzdE5hbWUiOiAiam9obiIsICJsYXN0TmFtZSI6ICJkb2UiLCAiZW1haWwiOiAiamRAZW1haWwuY29tIn0="
        publish_time:
          type: string
          format: date-time
          example: "2023-02-15T22:27:51.254590+00:00"
    GooglePubSubPushEvent:
      type: object
      required:
        - message
        - subscription
      properties:
        message:
          $ref: '#/components/schemas/GooglePubSubPushMessage'
        subscription:
          type: string
          example: projects/myproject/subscriptions/mysubscription
