# coding: utf-8

"""
    Testing

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class UsersAdded(BaseModel):
    """
    UsersAdded
    """
    status: StrictStr = Field(...)
    num_requested: StrictInt = Field(..., alias="numRequested")
    num_existed: StrictInt = Field(..., alias="numExisted")
    num_added: StrictInt = Field(..., alias="numAdded")
    __properties = ["status", "numRequested", "numExisted", "numAdded"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UsersAdded:
        """Create an instance of UsersAdded from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UsersAdded:
        """Create an instance of UsersAdded from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UsersAdded.parse_obj(obj)

        _obj = UsersAdded.parse_obj({
            "status": obj.get("status"),
            "num_requested": obj.get("numRequested"),
            "num_existed": obj.get("numExisted"),
            "num_added": obj.get("numAdded")
        })
        return _obj

