name: mongo-community
version: "4.2.6"
username: mongo
password: password123
database: admin
roles: false
replicas: 3
persistenceType: local
compressionType: zstd
memoryMin: 4000M
memoryMax: 4000M
cpuMin: 4000m
cpuMax: 4000m
persistence:
  data:
    storage: 20Gi
    storageClass: standard
  logs:
    storage: 2Gi
    storageClass: standard