/**
 * Testing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("HealthApi", () => {
  let instance: api.HealthApi
  beforeEach(function() {
    instance = new api.HealthApi(config)
  });

  test("getHealth", () => {
    return expect(instance.getHealth({})).resolves.toBe(null)
  })
})

describe("UserApi", () => {
  let instance: api.UserApi
  beforeEach(function() {
    instance = new api.UserApi(config)
  });

  test("addUsers", () => {
    const body: Array<api.User> = undefined
    return expect(instance.addUsers(body, {})).resolves.toBe(null)
  })
  test("getUsers", () => {
    const offset: number = 56
    const limit: number = 56
    const sort: string = "sort_example"
    return expect(instance.getUsers(offset, limit, sort, {})).resolves.toBe(null)
  })
})

