{{ if ne .Values.persistenceType  "local" }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-metrics-password
type: Opaque
stringData:
  password: {{ .Values.password }}
  username: metrics
{{ end }}