apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.name }}
spec:
  members: {{ .Values.replicas }}
  type: ReplicaSet
  version: {{ .Values.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.username }}
      db: {{ .Values.database }}
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ .Values.name }}-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: restore
          db: admin
        - name: backup
          db: admin
      scramCredentialsSecretName: {{ .Values.name }}-scram
  
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: {{ .Values.compressionType }}
    net.compression.compressors: {{ .Values.compressionType }}
  
  {{ if ne .Values.persistenceType  "local" }} 
  prometheus:
    passwordSecretRef: 
      name: {{ .Values.name }}-metrics-password
    username: metrics
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: {{ .Values.persistence.data.storageClass }}
            resources:
              requests:
                storage: {{ .Values.persistence.data.storage }}
        - metadata:
            name: log-volume
          spec:
            storageClassName: {{ .Values.persistence.logs.storageClass }}
            resources:
              requests:
                storage: {{ .Values.persistence.logs.storage }}
  {{ end }}
