# coding: utf-8

"""
    Testing

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.users_added import UsersAdded  # noqa: E501
from openapi_client.rest import ApiException

class TestUsersAdded(unittest.TestCase):
    """UsersAdded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UsersAdded
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersAdded`
        """
        model = openapi_client.models.users_added.UsersAdded()  # noqa: E501
        if include_optional :
            return UsersAdded(
                status = 'success', 
                num_requested = 2, 
                num_existed = 1, 
                num_added = 1
            )
        else :
            return UsersAdded(
                status = 'success',
                num_requested = 2,
                num_existed = 1,
                num_added = 1,
        )
        """

    def testUsersAdded(self):
        """Test UsersAdded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
