# coding: utf-8

"""
    Testing

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_users(self):
        """Test case for add_users

        Add Users  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get Users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
